#!/usr/bin/env python

import argparse
import tempfile
from subprocess import call
from notpy import Notary, config

authtoken = config.DEVTOKEN
n = Notary(authtoken)


def newnote():
    with tempfile.NamedTemporaryFile(suffix=".tmp") as f:
        call([config.EDITOR, f.name])
        n.makenote(open(f.name).read())


if __name__ == '__main__':
    newnote()
